services:
  ambed:
    container_name: ambed
    hostname: ambed
    image: cbodden/ambed-docker:latest
    restart: unless-stopped
#    privileged: true
    devices:
      - /dev/bus/usb/001/003:/dev/bus/usb/001/003
      - /dev/bus/usb/001/004:/dev/bus/usb/001/004
    ports:
      - 10100:10100/udp
      - 10101-10199:10101-10199/udp
